endpoints:
    enabled: true
    sensitive: false
management:
    port: 8080
    ssl:
     enabled: false

info:
    version: ${project.version}
logging:
    level:
        com:
            birse: DEBUG
        org:
            springframework:
                web: INFO
person:
    service:
        url: ${person_service_name}
spring:
    boot:
        admin:
            client:
                service-url: http://web-service:8080
            url: http://admin:8123
version: ${project.version}
server:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: password
        keyAlias: tomcat
        keyStoreType: PKCS12
