version: '3'
services:

  applicationOne:
      image: @group@/application1:@version@
      ports:
        - "8081:8080"
  applicationTwo:
      image: @group@/application2:@version@
      ports:
        - "8082:8080"
  data-service:
      image: @group@/data-service:@version@
      ports:
        - "8083:8080"
  web-service:
      image: @group@/web-server:@version@
      ports:
        - "8084:8080"