version: '3'
services:

  person-service:
      hostname: person-service
      ports:
        - "9001:8000"
      environment:
        - JAVA_OPTS=-Xmx150m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n
  person-data-service:
      links:
        - mysql:database
  mysql:
      image: mysql:8.0.1
      hostname: database
      command: [--character-set-server=utf8, --collation-server=utf8_bin]
      environment:
        MYSQL_ROOT_PASSWORD: @database_password@
        MYSQL_DATABASE: @database_name@
      restart: on-failure
