version: '3'
services:
  person-service:
      image: @group@/person-service:@version@
  person-data-service:
      image: @group@/person-data-service:@version@
  web-service:
      image: @group@/web-server:@version@
      ports:
        - "8084:8080"