version: '3'
services:
  person-service:
      image: @group@/person-service:@version@
      environment:
        - JAVA_OPTS= -Xmx200m
  person-data-service:
      image: @group@/person-data-service:@version@
      environment:
        - JAVA_OPTS= -Xmx200m
  discovery-service:
      image: @group@/discovery-service:@version@
      ports:
        - "8761:8761"
  web-service:
      image: @group@/web-server:@version@
      ports:
        - "80:8080"
      environment:
        - JAVA_OPTS= -Xmx200m